project:
  type: website
  output-dir: docs

website:
  title: "Seoncheol Park"
  site-url: https://seoncheolpark.github.io
  navbar:
    collapse: true
    collapse-below: sm
    logo: images/02.svg
    href: http://stat.hanyang.ac.kr
    background: primary
    search: true
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
      - projects.qmd
      - students.qmd
      - text: "Courses"
        menu:
        - text: "Sataistical Methods for Data Analysis (2025 Fall)"
          href: https://seoncheolpark.github.io/course-compstat
        - text: "Statistical Data Science (2025 Fall)"
          href: https://seoncheolpark.github.io/course-ml
    right: 
      - icon: github
        href: https://github.com/SeoncheolPark
  page-footer: "Â© Copyright 2026, Seoncheol Park"
format:
  html:
    theme: 
      light: [minty, theme.scss]
      dark: [minty, theme-dark.scss]
    fontsize: 1.1em
    linestretch: 1.7
    toc: true

editor: visual

